# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=40)),
                ('auth', models.URLField()),
                ('name', models.CharField(max_length=80)),
            ],
        ),
    ]
