# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getfhir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_state',
            name='auth',
            field=models.URLField(db_index=True),
        ),
        migrations.AlterField(
            model_name='session_state',
            name='name',
            field=models.CharField(db_index=True, max_length=80),
        ),
    ]
