# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getfhir', '0002_auto_20160410_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_state',
            name='code',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
