# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getfhir', '0003_session_state_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_state',
            name='atoken',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='session_state',
            name='rtoken',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
