# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 05:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('getfhir', '0004_auto_20160416_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_state',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 5, 12, 59, 578824, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
